targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/app/view/root_wrapper.dart
          - lib/home/view/home_page.dart
          - lib/posts/view/post_page.dart
          - lib/posts/view/sliver_posts_tab_view.dart
          - lib/posts/view/sliver_fav_posts_tab_view.dart
      auto_route_generator:auto_router_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/routing/routing.dart

