name: posts_app
description: Posts App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
