name: posts_app
description: Posts App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  app_ui:
    path: packages/app_ui/
  auto_route: ^9.2.2
  bloc: ^8.1.4
  dio: ^5.7.0
  dio_posts_api:
    path: packages/posts_api/dio_posts_api/
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  posts_api:
    path: packages/posts_api/posts_api/
  skeletonizer: ^1.4.2
  sliver_tools: ^0.2.12

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  file: ^7.0.1
  flutter_cache_manager: ^3.4.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  path: ^1.9.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
